### ISSUE TITLE
ppo experiments

### ISSUE THREAD

**Issue by hotco87** [kachayev/car-racing-attention-agent#2]
I am so grateful that there is an implementation for the paper I am interested in.
When I checked the ReadMe document, there was no exp2 ppo. Could it be that the agent was not trained with the ppo algorithm?

**Comment by kachayev** [comment]
Hey Joo, I'm glad you found the implementation helpful!

The agent was not trained with PPO in the original paper. I've added this as a baseline comparison. Well, that's true for all experiments: all of them implemented to build up better understanding of the learned agent, they are not part of the original paper.

Not sure why I didn't mention it in the README, maybe because learning is way to slow. I guess this shouldn't be much of a problem: the code is working, you can run it the same way other experiments are launched. Do you have troubles running it?
